In [2]:
import requests
import os
import json
from dotenv import load_dotenv

# .env 파일에서 환경 변수 로드
load_dotenv()

client_id = os.getenv("NAVER_CLIENT_ID")  # .env 파일의 NAVER_CLIENT_ID
client_secret = os.getenv("NAVER_CLIENT_SECRET")  # .env 파일의 NAVER_CLIENT_SECRET

headers = {
    'X-Naver-Client-Id': client_id,
    'X-Naver-Client-Secret': client_secret,
}
def search_shops(query):
    # query string 문자열을 dict  선언
    payload = {
        'query': query,#'가디건',
        'display': 50,
        'sort': 'sim'
    }

    url = 'https://openapi.naver.com/v1/search/shop.json' #?query=파이썬&display=100&sort=sim


    # requests get(url, params, headers) 요청 
    res = requests.get(url, params=payload, headers=headers)
    items_data = res.json()['items']

    with open('data/shops.json', 'w', encoding='utf-8') as file:
        json.dump(items_data, file, ensure_ascii=False, indent=4)

In [3]:
search_shops("가디건")

In [4]:
import pandas as pd
df_shops = pd.read_json('data/shops.json', encoding='utf-8')

df_shops.head()

,title,link,image,lprice,hprice,mallName,productId,productType,brand,maker,category1,category2,category3,category4
0,백화점3-5일배송 폴로 <b>가디건</b> 걸즈 걸스 랄프로렌 꽈배기 블랙 화이트 ...,https://smartstore.naver.com/main/products/667...,https://shopping-phinf.pstatic.net/main_842166...,64900,,나우인뉴욕,84216650390,2,폴로랄프로렌,폴로랄프로렌,패션의류,여성의류,카디건,
1,봄 가을 간절기 라운드 루즈핏 크롭 <b>가디건</b> 레드 그린 핑크 화이트 블랙...,https://smartstore.naver.com/main/products/546...,https://shopping-phinf.pstatic.net/main_830114...,19900,,ARUMY,83011442056,2,,,패션의류,여성의류,카디건,
2,[백화점3-5일배송] 폴로 <b>가디건</b> 니트 걸즈 랄프로렌 블랙 화이트 핑크...,https://smartstore.naver.com/main/products/845...,https://shopping-phinf.pstatic.net/main_859949...,63900,,트위티 155,85994962324,2,폴로랄프로렌,폴로랄프로렌,패션의류,여성의류,카디건,
3,부드러운 캐시미어 크롭 <b>가디건</b> 숏 라운드 니트<b>가디건</b> 여성 ...,https://smartstore.naver.com/main/products/482...,https://shopping-phinf.pstatic.net/main_823726...,18900,,코이블리,82372678315,2,,,패션의류,여성의류,카디건,
4,[백화점] 폴로 <b>가디건</b> 걸즈 케이블 꽈배기 니트,https://smartstore.naver.com/main/products/111...,https://shopping-phinf.pstatic.net/main_886518...,69000,,세컨찬스라이프,88651894622,2,폴로랄프로렌,폴로랄프로렌,패션의류,여성의류,카디건,

In [5]:
maxdiscount = 50000
df_shops.loc[df_shops['lprice'] <= maxdiscount,['brand','lprice','mallName','link']].sort_values(by='lprice',ascending=True).reset_index(drop=True)

,brand,lprice,mallName,link
0,,13100,네이버,https://search.shopping.naver.com/catalog/5369...
1,H&M,17512,네이버,https://search.shopping.naver.com/catalog/5178...
2,,18900,코이블리,https://smartstore.naver.com/main/products/482...
3,,18900,코이블리,https://smartstore.naver.com/main/products/438...
4,,19800,로이앤한나,https://smartstore.naver.com/main/products/490...
5,,19900,ARUMY,https://smartstore.naver.com/main/products/546...
6,리스트,23000,네이버,https://search.shopping.naver.com/catalog/5114...
7,,23900,고고하니,https://smartstore.naver.com/main/products/559...
8,,24800,베이지블랑.,https://smartstore.naver.com/main/products/519...
9,,24900,ARUMY,https://smartstore.naver.com/main/products/995...
10,리스트,24940,네이버,https://search.shopping.naver.com/catalog/4958...
11,,27000,건강한생활82,https://smartstore.naver.com/main/products/798...
12,비비안웨스트우드,28070,네이버,https://search.shopping.naver.com/catalog/4347...
13,,29800,미드시티 여성니트,https://smartstore.naver.com/main/products/100...
14,,29900,지읒이응,https://smartstore.naver.com/main/products/539...
15,제너럴아이디어,31416,네이버,https://search.shopping.naver.com/catalog/4954...
16,제너럴아이디어,32400,네이버,https://search.shopping.naver.com/catalog/5328...
17,쉬즈미스,36910,네이버,https://search.shopping.naver.com/catalog/4962...
18,벤시몽,37650,네이버,https://search.shopping.naver.com/catalog/5337...
19,사색,39700,사색,https://smartstore.naver.com/main/products/115...
20,,39800,왓위웨어,https://smartstore.naver.com/main/products/529...
21,,42000,ttoyuni,https://smartstore.naver.com/main/products/904...
22,사색,43700,사색,https://smartstore.naver.com/main/products/113...
23,벤시몽,44910,네이버,https://search.shopping.naver.com/catalog/5323...
24,로엠,44910,네이버,https://search.shopping.naver.com/catalog/5267...
25,,49500,루나드엘,https://smartstore.naver.com/main/products/997...

In [ ]:
df_shops.loc[df_shops['mallName'] == '네이버','lprice':'brand'].sort_values(by='lprice',ascending=True).reset_index(drop=True)

    lprice hprice mallName    productId  productType     brand
0    13100             네이버  53690259105            1
1    17512             네이버  51781610172            1       H&M
2    23000             네이버  51143733510            1       리스트
3    24940             네이버  49580876217            1       리스트
4    28070             네이버  43475137325            1  비비안웨스트우드
5    31416             네이버  49541497760            1   제너럴아이디어
6    32400             네이버  53287208769            1   제너럴아이디어
7    36910             네이버  49625464649            1      쉬즈미스
8    37650             네이버  53373694627            1       벤시몽
9    44910             네이버  53232763110            1       벤시몽
10   44910             네이버  52675721484            1        로엠
11   80100             네이버  49714141886            1      라코스테
12   85980             네이버  53126962083            1
13  143100             네이버  49912758699            1      라코스테
14  174090             네이버  50705955349            1      라코스테

In [9]:
def filter_shops(df, keyword, search_type='mall'):
    
    if search_type == 'mall':
        condition = df['mallName'] == keyword
    elif search_type == 'brand':
        condition = df['brand'] == keyword
    else:
        raise ValueError("search_type은 'mall' 또는 'brand'만 가능합니다.")

    return (
        df.loc[condition, 'lprice':'brand']
          .sort_values(by='lprice')
          .reset_index(drop=True)
    )

filter_shops(df_shops,'라코스테','brand')

   lprice hprice mallName    productId  productType brand
0   80100             네이버  49714141886            1  라코스테
1  143100             네이버  49912758699            1  라코스테
2  174090             네이버  50705955349            1  라코스테